### ISSUE TITLE
Alpine 3.11 Version

### ISSUE THREAD

**Issue by jseiser** [Docker-Hub-frolvlad/docker-alpine-glibc#38]
Any chance you can add a build of 3.11?

It would get around some current CVE's that exist around curl and Alpine 3.10

I would submit a pull request, but I dont see how you are building.

**Comment by frol** [comment]
I will do it today

**Comment by frol** [comment]
Resolved in https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/commit/c12a5736b5812ac56c597da78be820d2ff7b6900. The builds are still in the queue; they usually take up to a few hours (given the amount of dependencies on my images).
