### ISSUE TITLE
Not reponse to docker stop

### ISSUE THREAD

**Issue by eisig** [Docker-Hub-frolvlad/docker-alpine-glibc#42]
1. run in terminal 1
```
docker run -it --rm --name test frolvlad/alpine-glibc
```
2. try stop in terminal2
```
time docker stop test
test

real	0m10.787s
user	0m0.032s
sys	0m0.018s
```
3. after 10s terminal 1 show
```
/ # ✘-KILL ~
```

system:
mac osx: 10.15.5
docker destop  Version 2.0.0.3 (31259)
Docker Engine: 18.09.2

**Comment by frol** [comment]
Try with the official `alpine` image and observe the same behavior. It seems to be just the way sh is implemented in the Alpine busybox. If you run your own application or a proper init process (e.g. `runit`) as the entry-point, you will be able to control the signals handling.
