### ISSUE TITLE
userid's not working since 2.32

### ISSUE THREAD

**Issue by eilandert** [Docker-Hub-frolvlad/docker-alpine-glibc#43]
Hello,

Since upgrade to 2.32 my application cannot find the user it used to run as. When reverting back to the docker with 2.31 it works as it always worked.

https://github.com/eilandert/dockerized/blob/master/rspamd-git/Dockerfile

Last line fails:
https://github.com/eilandert/dockerized/blob/master/rspamd-git/bootstrap.sh

**Comment by frol** [comment]
That is odd, I have no idea how this can be related :-(

**Comment by eilandert** [comment]
Ok this is strange. When I build the docker local with docker-compose build it works fine, when building it through hub.docker.com it shows the strange uid behaviour.  investigating

**Comment by eilandert** [comment]
Only thing I could thing off was turning off the caching layers om hub.docker.com

but still

rspamd       | 2020-08-18 01:36:48 #0(main) <a16f0f>; main; detect_priv: user specified does not exists (Inappropriate ioctl for device), aborting

Well, going back to 2.31 for a while, i'll poke around when I have more time.
