### ISSUE TITLE
Update Dockerhub Image frequently

### ISSUE THREAD

**Issue by worldworm** [Docker-Hub-frolvlad/docker-alpine-glibc#45]
Hi,
this Docker image in Dockerhub with the "latest" tag is now over 5 months old.

Please run your build process/pipeline regularly even without new commits in this repo to get regular security updates of the base images.

Thanks!

**Comment by frol** [comment]
Thanks for pinging me! I pushed the rebuild button (and will follow up with the rest of my images). I would love Docker Hub fix their bug of automatic builds on base image change (it should get my images updated automatically according to the configuration I have, but it does not).
