### ISSUE TITLE
Library path?

### ISSUE THREAD

**Issue by ambs** [Docker-Hub-frolvlad/docker-alpine-glibc#47]
Hi
First things first, thanks for this image, that promises to be useful for me.
But I am having a little issue. How to run `ldconfig`?
It looks it doesn't do a thing...?

```
/app # ldconfig -v /usr/lib
/app # ldconfig -v /usr/local/lib/
```

This makes my app to fail:

```
/app # j2kdriver --version
j2kdriver: error while loading shared libraries: libawj2k.so: cannot open shared object file: No such file or directory
```
But if I used `LD_LIBRARY_PATH`:
```
/app # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib
/app # j2kdriver --version
Warning: Unrecognized option `--version' ignored.
```
I can go on, for now, with the env var, but I would like to get rid of it.
Ideas?
Thanks

**Comment by frol** [comment]
Use `/usr/glibc-compat/sbin/ldconfig`

**Comment by ambs** [comment]
Thank you. Probably add that in the readme?
Cheers

**Comment by frol** [comment]
@ambs Would you mind submitting a PR? I am quite under water with other tasks

**Comment by ambs** [comment]
Aren't we all? 🙈  But sure, during the weekend I'll try. 😆
