### ISSUE TITLE
Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37

### ISSUE THREAD

**Issue by leonchen83** [Docker-Hub-frolvlad/docker-alpine-glibc#50]
I use graalvm create a mostly static native image that only depends glibc.
It works fine in docker `frolvlad/alpine-glibc` (or maybe not fully tested. )
but when I use `ldd` to check dependencies found some error following
```
bash-5.1# ldd misc
	/lib64/ld-linux-x86-64.so.2 (0x7fd723484000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fd723484000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fd723484000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fd723484000)
	ld-linux-x86-64.so.2 => /lib/ld-linux-x86-64.so.2 (0x7fd72002c000)
Error relocating /lib/ld-linux-x86-64.so.2: unsupported relocation type 37
Error relocating misc: __strtok_r: symbol not found
Error relocating misc: __strdup: symbol not found
Error relocating misc: __sprintf_chk: symbol not found
```
so I want to ask can I ignore this error?

**Comment by frol** [comment]
`ldd` is not working well for non-musl binaries. See this comment for details: https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/issues/34#issuecomment-521536816
