### ISSUE TITLE
Alpine 3.14.3 is available

### ISSUE THREAD

**Issue by mtcolman** [Docker-Hub-frolvlad/docker-alpine-glibc#52]
Hi @frol, alpine 3.14.3 is out now and has some bug fixes, but this image hasn't been updated?

```
alpine:3.14.3
Last pushed12 days agobydoijanky
```

```
frolvlad/alpine-glibc:alpine-3.14_glibc-2.33
Last pushed2 months agobyfrolvlad
```

Is there any chance it could please be updated?

Also, is there any possibility you could please release images named in such as way to track the alpine releases, e.g. `frolvlad/alpine-glibc:alpine-3.14.3_glibc-2.33`?

Thanks.

**Comment by frol** [comment]
I bumped 3.14 images and also created 3.15 tags (& updated `latest`)
