### ISSUE TITLE
/lib64/ld-linux-x86-64.so.2 points to musl

### ISSUE THREAD

**Issue by pablosole** [Docker-Hub-frolvlad/docker-alpine-glibc#59]
On the latest version of the container as of today, /lib/ld-linux-x86-64.so.2 points to glibc but /lib64 points to musl. This means depending on how your binary was linked it's not really using glibc.

Latest build that I can see that has both /lib and /lib64 pointing to glibc was `alpine-3.11_glibc-2.31`.

I think the root cause was this https://github.com/sgerrand/alpine-pkg-glibc/commit/ddfe092f3d91c19f6cf8cb9f2938e088db4bfa8f

**Comment by frol** [comment]
I believe you should report it to https://github.com/sgerrand/alpine-pkg-glibc and then this repo will get the update adopted.
