### ISSUE TITLE
Alpine 3.18 based image

### ISSUE THREAD

**Issue by wholtz** [Docker-Hub-frolvlad/docker-alpine-glibc#63]
Looking forward to a Alpine 3.18 based image for use in the [micromamba-docker](https://github.com/mamba-org/micromamba-docker) project.

**Comment by frol** [comment]
Sorry for the delay. I have just upgraded images to Alpine 3.18, but I have to keep glibc 2.34 as 2.35 is mostly broken (https://github.com/sgerrand/alpine-pkg-glibc/issues/210) and newer versions has not been packaged yet.
