### ISSUE TITLE
aws-cli doesn't work in the latest docker image

### ISSUE THREAD

**Issue by vbnvaidy** [Docker-Hub-frolvlad/docker-alpine-glibc#71]
Hello, I use the image from https://hub.docker.com/r/frolvlad/alpine-glibc/tags. But the aws cli is not working on latest image where the alpine base version is 3.19, where as it works fine on alpine 3.18.

I am looking for inputs on how to make aws cli work on the latest image since the latest version of alpine 3.19 addresses many security vulnerabilities

**Comment by frol** [comment]
@vbnvaidy Have you installed aws-cli from alpine packages? Can you share a reproducible example and screenshots of how exactly it "doesn't work"?

**Comment by vbnvaidy** [comment]
@frol I install aws-cli by apk add aws-cli and I didn't see the error any more. I get the segmentation error when I download the package, extract it and transfer the contents into the docker image and then run ./install command to install aws-cli in the image. Thanks for your inputs and installing aws-cli from alpine packages fixed the issue.
