### ISSUE TITLE
looking for alpine 3.20 version of this image

### ISSUE THREAD

**Issue by vbnvaidy** [Docker-Hub-frolvlad/docker-alpine-glibc#72]
Hi @frol , I am pulling the latest version of this image from docker hub. I still see that the alpine version is 3.19. I would like to know to if there are any plans to release this image with alpine 3.20 version.

**Comment by frol** [comment]
Thanks for the reminder. Resolved in https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/commit/f7fa1b788f4fb91c81a62a570a31f84edcdf56e7
